/*
    https://store.youzan.com 有个全局对象_global
*/

_global.debug = true;
_global.js = {
    "js_compress": false,
    "css_compress": false,
    "use_js_cdn": false,
    "use_css_cdn": false,
    "message_report": true,
    "checkbrowser": false,
    "hide_wx_nav": true,
    "qn_public": "kdt_img",
    "qn_private": "kdt-private"
}



_global = {
    "kdt_id": 40497547,
    "user_id": "757433560",
    "run_mode": "online",
    "debug": false,
    "project": "default",
    "online_debug": false,
    "js": {
        "js_compress": true,
        "css_compress": true,
        "use_js_cdn": true,
        "use_css_cdn": true,
        "message_report": true,
        "checkbrowser": true,
        "hide_wx_nav": true,
        "qn_public": "kdt_img",
        "qn_private": "kdt-private"
    },
    "query_path": "/member/order",
    "query_key": null,
    "real_query_path": "get:/member/order/index.html",
    "module": "member",
    "controller": "Member_Order_Controller",
    "action": "index",
    "full_action": "getIndexHtml",
    "method": "get",
    "format": "html",
    "account": "+86-17365367130",
    "sign": "",
    "kdtnote_fans_id": 0,
    "nick_name": "17365367130",
    "gender": 0,
    "avatar": "https://img.yzcdn.cn/upload_files/no_pic.png?imageView2/2/w/280/h/280/q/75/format/webp",
    "shop_id": "50939164",
    "shop_type": 2,
    "company_id": 0,
    "team_status": {
        "weixin_pay": 1,
        "weixin_pay_address": 0,
        "alipay": 1,
        "alipay_sign": 0,
        "weixin_bind": 1,
        "weibo_bind": 0,
        "alipay_status": 0,
        "weixin_server": 0,
        "weixin_menu": 0,
        "weixin_subscribe": 1,
        "weixin_no": 0,
        "weixin_oldsub": 0,
        "team_certificate": 0,
        "team_init": 1,
        "qr_code": 1,
        "no_fans_buy": 0,
        "is_delete": 0,
        "hide_shopping_cart": 0,
        "other_shop": 0,
        "pp_shop": 0,
        "union_pay": 1,
        "peer_pay": 0,
        "feature_title": 1,
        "team_change": 0,
        "weixin_unbind": 1,
        "pp_authenticated": 0,
        "pp_guarantee_compensation": 0,
        "cod_pay": 0,
        "weixin_pay_origin": 0,
        "weixin_pay_big_unbind": 1,
        "weixin_pay_big_sign": 0,
        "is_gift": 0,
        "taobao_order_import": 0,
        "weixin_service": 0,
        "weixin_certificate": 0,
        "team_contact_finish": 0,
        "team_physical": 0,
        "direct_seller": 0,
        "bd_pay": 1,
        "team_mobile_certificate": 1,
        "skip_team_certificate": 0,
        "wxpay_test": 0,
        "is_wish": 0,
        "is_drawal_lock": 0,
        "is_trade_lock": 0,
        "weixin_certsub": 0,
        "is_message_lock": 0,
        "message_menu": 0,
        "user_management": 0,
        "account_management": 0,
        "oauth_permission": 0,
        "small_store": 0,
        "mutil_customer": 0,
        "business_message": 0,
        "card_coupon": 0,
        "material_management": 0,
        "vip_customer": 0,
        "tiegan_customer": 0,
        "ic_customer": 0,
        "is_secured_transactions": 1,
        "is_realtime_account": 0,
        "buy_record": 1,
        "secured_transactions_pop": 1,
        "show_web_im": 0,
        "customer_reviews": 1,
        "fx_77": 0,
        "oversea_edition": 0,
        "goods_recommend": 1,
        "business_customer": 0,
        "team_return_address_finish": 0,
        "margin": 0,
        "show_wsc_web_im": 1,
        "display_service_QRCode": 1,
        "customer_reviews_all": 0,
        "team_certificate_gf": 0,
        "fee_customer": 0,
        "team_close": 0,
        "team_protect": 1,
        "not_show_in_mjb": 0,
        "show_sold_out_goods": 0,
        "wxpay_auth_dir_is_https": 0,
        "hide_top_bar": 1,
        "pf_no_commission": 0,
        "use_self_logo": 0,
        "superstore_customer": 0,
        "team_certificate_md": 0,
        "showcase_forbid_creation": 0,
        "superstore_protect": 1,
        "superstore_close": 0,
        "is_weixin_mass_lock": 0,
        "is_weixin_material_lock": 0,
        "wsc_customer": 0,
        "wsc_protect": 0,
        "wsc_close": 0,
        "is_goods_create_lock": 0,
        "is_identity_card_required": 0,
        "sign_overseas_protocol": 0,
        "is_recycled": 0,
        "is_shop_type_modifying": 0
    },
    "mp_data": {
        "team_name": "宝信零售",
        "business": "[{\"value\":\"19\",\"text\":\"\\u65e5\\u7528\\u767e\\u8d27\"}]",
        "business_id": "19",
        "store_url": "",
        "contact_name": "17365367130",
        "mobile": "17365367130",
        "country_code": "+86",
        "qq": "",
        "company_id": 0,
        "logo": "https://img.yzcdn.cn/public_files/2016/05/13/8f9c442de8666f82abaf7dd71574e997.png",
        "team_type": "7"
    },
    "lifecycle": {
        "product_lifecycle": {
            "retail": {
                "current_status": "try",
                "begin_time": "2018-03-11 10:15:52",
                "end_time": "2018-03-18 10:15:52"
            }
        }
    },
    "team_admin": {"level": 1},
    "isNewUI": true,
    "isSuperStore": true,
    "isNewRetail": true,
    "sourceType": 7,
    "custom_domain": "",
    "usePermitMenu": true,
    "dsp": 0,
    "levelMenus": {
        "firstLevelMenuList": {
            "100": {
                "menuItemId": 100,
                "name": "概况",
                "biz": "retail",
                "perms": null,
                "icon": "icon-dashboard",
                "url": "//store.youzan.com/dashboard/index/index",
                "category": "",
                "subtitle": "",
                "description": "概况",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": null,
                "isActive": false,
                "isAccessible": true
            },
            "101": {
                "menuItemId": 101,
                "name": "商品",
                "biz": "retail",
                "perms": null,
                "icon": "icon-goods",
                "url": "//store.youzan.com/goods/goods/storage",
                "category": "",
                "subtitle": "商品中心",
                "description": "商品",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [36028796482093056, 0, 0, 0, 0, 1024, 140737488355328]},
                "isActive": false,
                "isAccessible": true
            },
            "102": {
                "menuItemId": 102,
                "name": "订单",
                "biz": "retail",
                "perms": null,
                "icon": "icon-order",
                "url": "//store.youzan.com/order/order/query",
                "category": "",
                "subtitle": "订单中心",
                "description": "订单查询、网店发货、到店自提、快速打单、退款维权、售后评价、订单设置",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [-36028797018963970, 2199023255555]},
                "isActive": false,
                "isAccessible": true
            },
            "103": {
                "menuItemId": 103,
                "name": "客户",
                "biz": "retail",
                "perms": null,
                "icon": "icon-fans",
                "url": "//store.youzan.com/member/manage/index",
                "category": "",
                "subtitle": "客户中心",
                "description": "客户",
                "version": 2,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 0, 0, 0, 0, 576460752303423500, 4473494184976]},
                "isActive": false,
                "isAccessible": true
            },
            "104": {
                "menuItemId": 104,
                "name": "数据",
                "biz": "retail",
                "perms": null,
                "icon": "icon-stat",
                "url": "//store.youzan.com/data/dashboard/index",
                "category": "",
                "subtitle": "数据中心",
                "description": "数据",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 130560, 0, 0, 0, 0, 281474976710656]},
                "isActive": false,
                "isAccessible": true
            },
            "105": {
                "menuItemId": 105,
                "name": "资产",
                "biz": "retail",
                "perms": null,
                "icon": "icon-assets",
                "url": "//store.youzan.com/assets/store/index",
                "category": "",
                "subtitle": "资产中心",
                "description": "资产",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 281475010134016, 0, 274877906944, 0, 0, 562949953421312]},
                "isActive": true,
                "isAccessible": true
            },
            "106": {
                "menuItemId": 106,
                "name": "营销",
                "biz": "retail",
                "perms": null,
                "icon": "icon-marketing",
                "url": "//store.youzan.com/shop/v2/ump/dashboard/index",
                "category": "",
                "subtitle": "应用和营销",
                "description": "营销",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 503316480]},
                "isActive": false,
                "isAccessible": true
            },
            "107": {
                "menuItemId": 107,
                "name": "网店",
                "biz": "retail",
                "perms": null,
                "icon": "icon-shop",
                "url": "//store.youzan.com/shop/v2/showcase/dashboard/index",
                "category": "",
                "subtitle": "店铺管理",
                "description": "网店",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 136902082560]},
                "isActive": false,
                "isAccessible": true
            },
            "108": {
                "menuItemId": 108,
                "name": "设置",
                "biz": "retail",
                "perms": null,
                "icon": "icon-setting",
                "url": "//store.youzan.com/setting/store/cashier",
                "category": "",
                "subtitle": "设置中心",
                "description": "设置",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 140600049401856, 0, 0, 0, 768]},
                "isActive": false,
                "isAccessible": true
            }
        },
        "secondLevelMenuList": [{
            "groupName": "",
            "parMenuItemId": "105",
            "subItemList": [{
                "menuItemId": 105101,
                "name": "资产概览",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/assets/store/index",
                "category": "",
                "subtitle": "",
                "description": "资产概览",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 131072]},
                "isActive": false,
                "isAccessible": true
            }, {
                "menuItemId": 105102,
                "name": "我的交易",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/assets/store/checking",
                "category": "",
                "subtitle": "",
                "description": "我的交易",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 262144]},
                "isActive": false,
                "isAccessible": true
            }, {
                "menuItemId": 105103,
                "name": "对账单",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/shop/v2/trade/bill/index#list",
                "category": "",
                "subtitle": "",
                "description": "对账单",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 524288]},
                "isActive": false,
                "isAccessible": true
            }, {
                "menuItemId": 105109,
                "name": "储值资金",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/shop/v2/trade/prepaidCard/index",
                "category": "",
                "subtitle": "",
                "description": "储值资金",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 281474976710656]},
                "isActive": false,
                "isAccessible": true
            }, {
                "menuItemId": 105105,
                "name": "保证金",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/shop/v2/trade/deposit/index",
                "category": "",
                "subtitle": "",
                "description": "",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 0, 0, 0, 0, 0, 562949953421312]},
                "isActive": false,
                "isAccessible": true
            }, {
                "menuItemId": 105110,
                "name": "礼品卡资金",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/shop/v2/trade/giftCard/index",
                "category": "",
                "subtitle": "",
                "description": "礼品卡资金",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 0, 0, 274877906944]},
                "isActive": false,
                "isAccessible": true
            }, {
                "menuItemId": 105104,
                "name": "服务中心",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/shop/v2/member/dashboard/index",
                "category": "",
                "subtitle": "",
                "description": "",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 1048576]},
                "isActive": true,
                "isAccessible": true
            }],
            "isActive": true
        }],
        "thirdLevelMenuList": {
            "105104101": {
                "menuItemId": 105104101,
                "name": "服务市场",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/shop/v2/member/dashboard/index",
                "category": "",
                "subtitle": "",
                "description": "",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 1048576]},
                "isActive": false
            },
            "105104102": {
                "menuItemId": 105104102,
                "name": "我的服务",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/shop/v2/member/order/index",
                "category": "",
                "subtitle": "",
                "description": "",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 281474976710656]},
                "isActive": true
            },
            "105104103": {
                "menuItemId": 105104103,
                "name": "订购记录",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/shop/v2/member/dashboard/index",
                "category": "",
                "subtitle": "",
                "description": "",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 281474976710656]},
                "isActive": false
            },
            "105104104": {
                "menuItemId": 105104104,
                "name": "我的礼包",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/shop/v2/member/dashboard/index",
                "category": "",
                "subtitle": "",
                "description": "",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 281474976710656]},
                "isActive": false
            },
            "105104105": {
                "menuItemId": 105104105,
                "name": "增值权益",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/shop/v2/member/dashboard/index",
                "category": "",
                "subtitle": "",
                "description": "",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 281474976710656]},
                "isActive": false
            },
            "105104106": {
                "menuItemId": 105104106,
                "name": "邀请奖励",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/shop/v2/member/dashboard/index",
                "category": "",
                "subtitle": "",
                "description": "",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 8388608]},
                "isActive": false
            },
            "105104107": {
                "menuItemId": 105104107,
                "name": "发票管理",
                "biz": "retail",
                "perms": null,
                "icon": "",
                "url": "//store.youzan.com/shop/v2/trade/invoice/index",
                "category": "",
                "subtitle": "",
                "description": "",
                "version": 3,
                "menuItemType": 0,
                "mapBizPerms": {"retail": [0, 16777216]},
                "isActive": false
            }
        },
        "forthLevelMenuList": [],
        "isLegalUrl": true,
        "widgetList": []
    },
    "url": {
        "base": "//www.youzan.com",
        "bbs": "http://bbs.youzan.com",
        "cdn": "//b.yzcdn.cn",
        "cdn_static": "https://b.yzcdn.cn/v2",
        "daxue": "http://xuetang.youzan.com",
        "fenxiao": "//fx.youzan.com",
        "fuwu": "https://fuwu.youzan.com",
        "img": "//img.youzan.com",
        "imgqn": "https://img.yzcdn.cn",
        "login": "//login.youzan.com",
        "open": "//open.youzan.com",
        "static": "https://static.youzan.com/v2",
        "trade": "https://trade.koudaitong.com",
        "v1": "https://www.youzan.com/v1",
        "v1_static": "//b.yzcdn.cn/v1",
        "v2": "//store.youzan.com/shop/v2",
        "wap": "https://h5.youzan.com/v2",
        "ws": "ws://s.im.youzan.com:83",
        "www": "//store.youzan.com/shop/v2",
        "youzan": "//www.youzan.com",
        "cloud": "https://dl.yzcdn.cn",
        "pf": "https://pifa.youzan.com",
        "uic": "https://uic.youzan.com",
        "store": "//store.youzan.com",
        "market": "https://pfmarket.youzan.com",
        "im": "https://b-im.youzan.com",
        "help": "//help.youzan.com",
        "materials": "//materials.youzan.com"
    }
}